export const TextRace: Record<string, string> = {
    aarakocra: 'Ааракокра',
    aasimar: 'Аасимар',
    autognome: 'Автогном',
    astralElf: 'Астральный эльф',
    bugbear: 'Багбир',
    vedalken: 'Ведалкен',
    verdan: 'Вердан',
    simicHybrid: 'Гибрид Симиков',
    gith: 'Гит',
    giff: 'Гифф',
    gnome: 'Гном',
    goblin: 'Гоблин',
    goliath: 'Голиаф',
    grung: 'Грунг',
    dwarf: 'Дварф',
    genasi: 'Дженази',
    dragonborn: 'Драконорождённый',
    harengon: 'Зайцегон',
    kalashtar: 'Калаштар',
    kender: 'Кендер',
    kenku: 'Кенку',
    centaur: 'Кентавр',
    kobold: 'Кобольд',
    warforged: 'Кованый',
    leonin: 'Леонин',
    locathah: 'Локата',
    loxodon: 'Локсодон',
    lizardfolk: 'Людоящер',
    minotaur: 'Минотавр',
    orc: 'Орк',
    plasmoid: 'Плазмоид',
    halfOrc: 'Полуорк',
    halfling: 'Полурослик',
    halfElf: 'Полуэльф',
    satyr: 'Сатир',
    owlin: 'Совлин',
    tabaxi: 'Табакси',
    tiefling: 'Тифлинг',
    tortle: 'Тортл',
    thriKreen: 'Три-крин',
    triton: 'Тритон',
    firbolg: 'Фирболг',
    fairy: 'Фэйри',
    hadozee: 'Хадози',
    hobgoblin: 'Хобгоблин',
    changeling: 'Чейнджлинг',
    human: 'Человек',
    shifter: 'Шифтер',
    elf: 'Эльф',
    yuanTi: 'Юань-ти',
    hexblood: 'Ведьмовская кровь',
    reborn: 'Возрождённый',
    dhampir: 'Дампир',
    customLineage: 'Своё происхождение'
};