import type { RaceKey } from "../types/dnd.ts";

export const TextRace: Record<RaceKey, string> = {
    aarakocra: 'Ааракокра',
    aasimar: 'Аасимар',
    autognome: 'Автогном',
    astralElf: 'Астральный эльф',
    bugbear: 'Багбир',
    vedalken: 'Ведалкен',
    verdan: 'Вердан',
    simicHybrid: 'Гибрид Симиков',
    gith: 'Гит',
    githzerai: 'Гитцерай',
    githyanki: 'Гитъянки',
    giff: 'Гифф',
    gnome: 'Гном',
    goblin: 'Гоблин',
    goliath: 'Голиаф',
    grung: 'Грунг',
    dwarf: 'Дварф',
    genasi: 'Дженази',
    dragonborn: 'Драконорождённый',
    deepGnome: 'Глубинный гном',
    duergar: 'Дуэргар',
    harengon: 'Зайцегон',
    kalashtar: 'Калаштар',
    kender: 'Кендер',
    kenku: 'Кенку',
    centaur: 'Кентавр',
    kobold: 'Кобольд',
    koboldsOfMidgard: 'Кобольд Мидгарда',
    warforged: 'Кованый',
    gearforged: 'Кованый (Мидгард)',
    leonin: 'Леонин',
    locathah: 'Локата',
    loxodon: 'Локсодон',
    eladrin: 'Эладрин',
    seaElf: 'Морской эльф',
    shadarKai: 'Шадар-кай',
    glitchling: 'Глючный',
    aven: 'Авен',
    revenant: 'Ревенант',
    lizardfolk: 'Людоящер',
    minotaur: 'Минотавр',
    orc: 'Орк',
    accursedTiefling: 'Анафемный тифлинг',
    hobgoblinFeywild: 'Хобгоблин из Страны Фей',
    humanOfMidgard: 'Люди Мидгарда',
    plasmoid: 'Плазмоид',
    halfOrc: 'Полуорк',
    halfling: 'Полурослик',
    winterfolkHalflings: 'Зиморождённые полурослики',
    halfElf: 'Полуэльф',
    satyr: 'Сатир',
    owlin: 'Совлин',
    tabaxi: 'Табакси',
    tiefling: 'Тифлинг',
    tortle: 'Тортл',
    thriKreen: 'Три-крин',
    triton: 'Тритон',
    firbolg: 'Фирболг',
    fairy: 'Фэйри',
    hadozee: 'Хадози',
    hobgoblin: 'Хобгоблин',
    changeling: 'Чейнджлинг',
    human: 'Человек',
    shifter: 'Шифтер',
    elf: 'Эльф',
    yuanTi: 'Юань-ти',
    hexblood: 'Ведьмовская кровь',
    reborn: 'Возрождённый',
    dhampir: 'Дампир',
    customLineage: 'Своё происхождение',
};