export const TextWeapons: Record<string, string> = {
    simpleMelee: 'Простое оружие',
    martialMelee: 'Воинское оружие',
    battleaxe: "Боевой топор",
    warhammer: "Боевой молот",
    warPick: "Боевой кир",
    blowgun: "Духовая трубка",
    dart: "Дротик",
    club: "Дубинка",
    greatclub: "Большая дубина",
    dagger: "Кинжал",
    whip: "Кнут",
    spear: "Копьё",
    javelin: "Метательное копьё",
    lightHammer: "Лёгкий молот",
    lightCrossbow: "Лёгкий арбалет",
    net: "Сеть",
    sickle: "Серп",
    quarterstaff: "Посох",
    sling: "Праща",
    handCrossbow: "Ручной арбалет",
    shortsword: "Короткий меч",
    shortbow: "Короткий лук",
    trident: "Трезубец",
    heavyCrossbow: "Тяжёлый арбалет",
    longbow: "Длинный лук",
    glaive: "Глефа",
    halberd: "Алебарда",
    greatsword: "Большой меч",
    handaxe: "Боевой топор"
};