export const TextWeapons: Record<string, string> = {
    simpleMelee: 'Простое оружие',
    martialMelee: 'Воинское оружие',
    quarterstaff: "Посох",
    mace: "Булава",
    club: "Дубинка",
    dagger: "Кинжал",
    spear: "Копьё",
    lightHammer: "Лёгкий молот",
    javelin: "Метательное копьё",
    greatclub: "Большая дубина",
    handaxe: "Боевой топор",
    sickle: "Серп",
    lightCrossbow: "Лёгкий арбалет",
    dart: "Дротик",
    shortbow: "Короткий лук",
    sling: "Праща",
    halberd: "Алебарда",
    battleaxe: "Боевой топор",
    warPick: "Боевой кир",
    warhammer: "Боевой молот",
    glaive: "Глефа",
    greatsword: "Большой меч",
    longbow: "Длинный лук",
    whip: "Кнут",
    shortsword: "Короткий меч",
    trident: "Трезубец",
    chain: "Цепь",
    handCrossbow: "Ручной арбалет",
    heavyCrossbow: "Тяжёлый арбалет",
    blowgun: "Духовая трубка",
    net: "Сеть"
};