export const TextWeapons: Record<string, string> = {
    simpleMelee: 'Простое оружие',
    martialMelee: 'Воинское оружие',

    quarterstaff: 'Боевой посох',
    mace: 'Булава',
    club: 'Дубинка',
    dagger: 'Кинжал',
    spear: 'Копьё',
    lightHammer: 'Лёгкий молот',
    javelin: 'Метательное копьё',
    greatclub: 'Палица',
    handaxe: 'Ручной топор',
    sickle: 'Серп',
    lightCrossbow: 'Лёгкий арбалет',
    dart: 'Дротик',
    shortbow: 'Короткий лук',
    sling: 'Праща',

    halberd: 'Алебарда',
    warPick: 'Боевая кирка',
    warhammer: 'Боевой молот',
    battleaxe: 'Боевой топор',
    glaive: 'Глефа',
    greatsword: 'Двуручный меч',
    lance: 'Длинное копьё',
    longsword: 'Длинный меч',
    whip: 'Кнут',
    shortsword: 'Короткий меч',
    maul: 'Молот',
    morningstar: 'Моргенштерн',
    pike: 'Пика',
    rapier: 'Рапира',
    greataxe: 'Секира',
    scimitar: 'Скимитар',
    trident: 'Трезубец',
    flail: 'Цеп',
    handCrossbow: 'Ручной арбалет',
    heavyCrossbow: 'Тяжёлый арбалет',
    longbow: 'Длинный лук',
    blowgun: 'Духовая трубка',
    net: 'Сеть'
};